services:
  dwh:
    image: postgres:17
    container_name: manufacturing-datawarehouse
    environment:
      POSTGRES_DB: dwh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    depends_on:
      - dwh
    working_dir: /usr/app
    ports:
      - "8080:8080"
    volumes:
      - ./dbt:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml

volumes:
  postgres_data:
